In [2]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [12]:
m=np.array([[1,5,2],
          [4,7,4],
          [2,0,9]]);
print(m)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [13]:
print('Matrix transpose\n',m.transpose(),'\n')
print('Matrix determinant\n',np.linalg.det(m),'\n')
m_inv=np.linalg.inv(m);
print('Matrix inverse\n',m_inv,'\n')
ider_m=np.dot(m,m_inv)
iden_m=np.round(np.abs(ider_m),0)
print('Prouduct of matrix and its traverse \n',iden_m)

Matrix transpose
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 

Matrix determinant
 -105.00000000000006 

Matrix inverse
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 

Prouduct of matrix and its traverse 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
eigen_vals,eigen_vecs=np.linalg.eig(m)
print('Eigen values\n',eigen_vals,'\n')
print('Eigen vector\n',eigen_vecs,'\n')

Eigen values
 [-1.32455532 11.32455532  7.        ] 

Eigen vector
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]] 



In [17]:
u,s,vt=np.linalg.svd(m)
print("getting SVD outputs:\n")
print("U:\n",u,"\n")
print("S:\n",s)
print("\nVT:\n",vt)

getting SVD outputs:

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079]

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]]


In [23]:
zeros_array=np.zeros((2,3),dtype=np.int32)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [22]:
ones_array=np.ones((1,3),dtype=np.int32)
print(ones_array)

[[1 1 1]]


In [24]:
#random number

In [43]:
import scipy as sp
import numpy as np
from statistics import mode 

In [25]:
nums=np.random.randint(1,20,size=(1,15))[0]
print("Data: ",nums)

Data:  [18 11 14  8  4  2  4  3 17  6  1 12 10  6  5]


In [44]:
print("Means: ",np.mean(nums))
print("Median: ",np.median(nums))
print("Mode: ",mode(nums))
print("SD: ",np.std(nums))
print("Variatiant: ",np.var(nums))
print("Skew: ",sp.stats.skew(nums))
print("kurtosis: ",sp.stats.kurtosis(nums))

Means:  8.066666666666666
Median:  6.0
Mode:  4
SD:  5.195724738239657
Variatiant:  26.995555555555555
Skew:  0.5266396836771182
kurtosis:  -0.9096244008019192


In [ ]:
#wite a code to generate 3 random numbers between 100 AND 999 which is divisible by 3

In [ ]:
#write a code generate 100 random lottary tickets and pick two lucky tickets from it as a winner
#the lottery number must be 10 digit long
#all 100 tickets must be unique
#generate a random list of 1000 numbers using randrange() method to pick lucky 2 tickets

In [ ]:
#wirte a code to generate a random password which the following conditions
#password length must be 10 chars long
#It must contains at least 2 uppercase ,1 digit and 